##jdbc:sqlserver://myrevtalent.database.windows.net:1433;database=revtalentdb;user=Deekshitha@myrevtalent;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
##
##spring.application.name=revtalent
##
##spring.datasource.url=jdbc:mysql://localhost:3306/revtalent
##spring.datasource.username=revtalentuser
##spring.datasource.password=revtalent123
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
##
##spring.jpa.hibernate.ddl-auto=update
#spring.application.name=revtalent
#
## Azure SQL Database Configuration
spring.datasource.url=jdbc:sqlserver://myrevtalent.database.windows.net:1433;database=revtalentdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=Deekshitha@myrevtalent
spring.datasource.password=Deekshu7494@#

server.port=8080

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
# Optional
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect