#
#
#
#
#spring.application.name=revtalent
#
#spring.datasource.url=jdbc:sqlserver://revtalent.database.windows.net:1433;database=revtalent;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#spring.datasource.username=Brundarika@revtalent
#spring.datasource.password=Brunda@1304
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#
#spring.jpa.hibernate.ddl-auto=update
#
#
## ================== MONGODB ==================
#spring.data.mongodb.uri=mongodb://localhost:27017/revtalent
#server.port=8080
#
#
## ================== OPTIONAL ==================
#spring.jackson.serialization.fail-on-empty-beans=false
#
#
